---

- name: Install XWindows
  package:
    name: xorg
    state: installed

- name: Install the Mali driver
  package:
    name: chip-mali-userspace
    state: installed

- name: Install NoDM
  package:
    name: nodm
    state: installed

- name: Configure NoDM
  copy:
    src: nodm.conf
    dest: /etc
    mode: 0644

- name: Install git
  package:
    name: git
    state: installed

- name: Install Tzatziffy drivers
  git:
    repo: "https://github.com/KoljaWindeler/CHIP_TZATZIFFY.git"
    dest: /opt/CHIP_TZATZIFFY

- name: Install the overlay
  shell: /opt/CHIP_TZATZIFFY/overlay/chip/install.sh
  args:
    creates: /lib/firmware/nextthingco/chip/dip-2a-2.dtbo

- name: Copy the updated xorg.conf into place
  copy:
    src: /opt/CHIP_TZATZIFFY/scripts/xorg.conf
    dest: /etc/X11
    remote_src: true
    backup: yes
    
- name: Install a Customized DWM
  copy:
    src: dwm
    dest: /usr/local/bin
    mode: 0755

- name: Create a /home/chip/.dwm directory
  file:
    dest: /home/chip/.dwm
    state: directory
    mode: 0700
    owner: chip
    group: chip

- name: Add the DWM autostart file
  copy:
    src: autostart.sh
    dest: /home/chip/.dwm/autostart.sh
    mode: 0500
    owner: chip
    group: chip

- name: Install the sudoers rule
  copy:
    src: carputer
    dest: /etc/sudoers.d
    mode: 0440
    owner: root
    group: root

- name: Install FLite Speech synthesis
  package: 
    name: "flite"
    state: "installed"

- name: Install GPSd
  package:
    name: "gpsd"
    state: "installed"

- name: Configure GPSd to use /dev/ttyUSB0
  lineinfile:
    path: /etc/default/gpsd
    regexp: "DEVICES="
    line: "DEVICES=\"/dev/ttyUSB0\""
    state: present

- name: Install Navit
  package:
    name: "navit"
    state: "installed"

- name: Create a /home/chip/.navit directory
  file:
    dest: /home/chip/.navit
    state: directory
    mode: 0755
    owner: chip
    group: chip

- name: Add the navit.xml file
  copy:
    src: navit.xml
    dest: /home/chip/.navit/navit.xml
    mode: 0644
    owner: chip
    group: chip

- name: Install Mopidy (MPD server)
  package:
    name: "mopidy"
    state: "installed"

- name: Install Glurp (MPD client)
  package:
    name: "glurp"
    state: "installed"

- name: Install stterm (a terminal)
  package:
    name: "stterm"
    state: "installed"

# Installs OBDII software

# Install Bluetooth management software if needed (for keyboard and OBDII)


