---

# Installs Tzatziffy drivers

# Installs Customized DWM

# Installs Navit

# Installs Mopidy

# Installs MPD Client

# Installs OBDII software

# Install Bluetooth management software if needed (for keyboard and OBDII)


