---

- name: Install Tzatziffy drivers
  git:
    repo: "https://github.com/KoljaWindeler/CHIP_TZATZIFFY.git"
    dest: /opt/

- name: Install the overlay
  command: /opt/CHIP_TZATZIFFY/overlay/chip/install.sh
    creates: /lib/firmware/nextthingco/chip/dip-2a-2.dtbo

- name: Copy the updated xorg.conf into place
  copy:
    src: /opt/CHIP_TZATZIFFY/scripts/xorg.conf
    dest: /etc/X11
    remote_src: true
    backup: yes
    
- name: Install a Customized DWM
  copy:
    src: dwm
    dest: /usr/local/bin

- name: Add the DWM autostart file
  copy:
    src: autostart.sh
    dest: /home/chip/.dwm/autostart.sh


- name: Install Navit
  package:
    name="navit"
    status="installed"

- name: Install Mopidy (MPD server)
  package:
    name="mopidy"
    status="installed"

- name: Install Glurp (MPD client)
  package:
    name="glurp"
    status="installed"

- name: Install stterm (a terminal)
  package:
    name="stterm"
    status="installed"

# Installs OBDII software

# Install Bluetooth management software if needed (for keyboard and OBDII)


